name: release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Docker images for ghcr.io
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      DOCKER_REGISTRY: ghcr.io
      DOCKER_IMAGE_BASE: ${{ github.repository }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Prover and Verifier and deb

      - name: Prover&Verifier image tags & labels
        id: meta-all
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_BASE }}
      - name: Prover&Verifier image build & push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta-all.outputs.tags }}
          labels: ${{ steps.meta-all.coutputs.labels }}

      - name: Extract binary from Docker image
        run: |
          container_id=$(docker create ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_BASE }})
          docker cp $container_id:/usr/bin/cpu_air_prover /tmp/cpu_air_prover
          docker cp $container_id:/usr/bin/cpu_air_verifier /tmp/cpu_air_verifier
          docker cp $container_id:/app/stone-prover.deb /tmp/stone-prover.deb
          docker rm $container_id

      - name: Verify file existence#2
        run: ls -l /tmp/cpu*

      - name: Upload files to a GitHub release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: /tmp/cpu_air*

      - name: Upload dep to a GitHub release
        id: create_release_deb
        uses: softprops/action-gh-release@v2
        with:
          files: /tmp/stone-prover.deb
